services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/emu-vault
      - node_modules:/emu-vault/node_modules
    depends_on:
      - postgres
    restart: always
    tty: true
    stdin_open: true
    env_file:
      - .env

  postgres:
    image: postgres:17
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  redis:
    image: "redis:latest"
    command: redis-server
    volumes:
      - "redis:/data"

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/emu-vault
      - /emu-vault/tmp
    depends_on:
      - redis
      - postgres
    env_file:
      - .env

volumes:
  node_modules:
  pg_data:
  redis:
