default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("DB_USERNAME", "emuvault") %>
  password: <%= ENV.fetch("DB_PASSWORD", "emuvault") %>

development:
  <<: *default
  database: emu_vault_development

test:
  <<: *default
  database: emu_vault_test

production:
  primary: &primary_production
    <<: *default
    database: emu_vault_production
    username: <%= ENV["DB_USERNAME"] %>
    password: <%= ENV["DB_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: emu_vault_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: emu_vault_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: emu_vault_production_cable
    migrations_paths: db/cable_migrate
